version: 2

project_name: pocket-admin

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build_cgo
    main: .
    binary: pocket-admin
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

  - id: build_noncgo
    main: .
    binary: pocket-admin
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

archives:
  - id: archive_noncgo
    builds: [build_noncgo]
    format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else if eq .Arch "arm" }}armv7
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README*
      - LICENSE*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch

release:
  draft: true
  mode: replace
  name_template: "v{{ .Version }}"
  extra_files:
    - glob: ./LICENSE*
    - glob: ./README*
    - glob: ./CHANGELOG*

source:
  enabled: true
  format: "zip"
  prefix_template: "{{ .ProjectName }}_{{ .Version }}"
